CREATE TABLE IF NOT EXISTS `tbl_far_bandeja_reaccion_paciente` (
  `id_bandeja` int(11) NOT NULL AUTO_INCREMENT,
  `id_paciente` int(11) NOT NULL,
  `id_medico` int(11) DEFAULT NULL,
  `id_reaccion` int(11) DEFAULT NULL,
  `estado` enum('NUEVO','VISTO','PROCESADO') NOT NULL DEFAULT 'NUEVO',
  `usuario_creacion` int(11) DEFAULT NULL,
  `fecha_creacion` datetime DEFAULT current_timestamp(),
  `usuario_visto` int(11) DEFAULT NULL,
  `fecha_visto` datetime DEFAULT NULL,
  `usuario_procesado` int(11) DEFAULT NULL,
  `fecha_procesado` datetime DEFAULT NULL,
  PRIMARY KEY (`id_bandeja`),
  KEY `idx_bandeja_paciente` (`id_paciente`),
  KEY `idx_bandeja_medico` (`id_medico`),
  KEY `idx_bandeja_reaccion` (`id_reaccion`),
  KEY `idx_bandeja_estado` (`estado`),
  KEY `idx_bandeja_usuario_creacion` (`usuario_creacion`),
  KEY `idx_bandeja_usuario_visto` (`usuario_visto`),
  KEY `idx_bandeja_usuario_procesado` (`usuario_procesado`),
  CONSTRAINT `fk_bandeja_paciente` FOREIGN KEY (`id_paciente`) REFERENCES `tbl_far_paciente` (`id_paciente`) ON DELETE CASCADE,
  CONSTRAINT `fk_bandeja_medico` FOREIGN KEY (`id_medico`) REFERENCES `tbl_far_medico` (`id_medico`) ON DELETE SET NULL,
  CONSTRAINT `fk_bandeja_reaccion` FOREIGN KEY (`id_reaccion`) REFERENCES `tbl_far_reaccion_adversa` (`id_reaccion`) ON DELETE SET NULL,
  CONSTRAINT `fk_bandeja_usuario_creacion` FOREIGN KEY (`usuario_creacion`) REFERENCES `tbl_seg_usuario` (`id_usuario`) ON DELETE SET NULL,
  CONSTRAINT `fk_bandeja_usuario_visto` FOREIGN KEY (`usuario_visto`) REFERENCES `tbl_seg_usuario` (`id_usuario`) ON DELETE SET NULL,
  CONSTRAINT `fk_bandeja_usuario_procesado` FOREIGN KEY (`usuario_procesado`) REFERENCES `tbl_seg_usuario` (`id_usuario`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;